### ISSUE TITLE
Please provide an example deployment manifest

### ISSUE THREAD

**Issue by slowbackspace** [cloudfoundry-community/memcache-release#12]
I am very new to the BOSH and I have a hard time completing the deployment manifest (OpenStack). Could you provide a full example? Thanks.

Edit:
Currently I am stuck at

```
Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'memcache_broker'. Errors are:
     - Unable to render templates for job 'memcache_broker'. Errors are:
       - Error filling in template 'config.yml.erb' (line 5: nil is not a symbol nor a string)
   - Unable to render jobs for instance group 'memcache'. Errors are:
     - Unable to render templates for job 'memcache_hazelcast'. Errors are:
       - Error filling in template 'config.yml.erb' (line 15: nil is not a symbol nor a string)
```

I can't find those files anywhere so I really don't have a clue what is missing.

Here is what I managed to get together
https://gist.github.com/slowbackspace/618a65f0e0e01efbf71a8b0fc3fa752d

**Comment by youngm** [comment]
I'll be doing a new final release probably Tuesday.  At that point the master documentation on master will match the code.  I'll help you get a manifest together then.

**Comment by youngm** [comment]
K, give it a try now with the new release 4 and let me know what error you get then.

**Comment by slowbackspace** [comment]
Thanks! V4 deployed without a problem.

**Comment by youngm** [comment]
The broker username is "servicebroker".  Good catch I'll add that to the docs.

**Comment by slowbackspace** [comment]
It already was in the docs, I just missed it. I edited my comment 2 minutes after I sent it :)

**Comment by youngm** [comment]
Excellent!  I'll close then.
